#source
. ~/.dotfiles/zsh/theme
. ~/.dotfiles/zsh/functions
. ~/.dotfiles/zsh/aliases

#plugins
. ~/.dotfiles/zsh/plugins/zsh-completions/zsh-completions.plugin.zsh
. ~/.dotfiles/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
. ~/.dotfiles/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# completion
autoload -U compinit
compinit

# suggestation color
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#555555'

#vi keybindings
bindkey -v

# bindkey to accept suggestation
bindkey '^_' autosuggest-accept

# history
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# options
setopt autocd sharehistory histignorealldups

#run fastfetch once
if [ -z "$FASTFETCH_RAN" ]; then
    fastfetch
    export FASTFETCH_RAN=1
fi


# Env
export TERMINAL=wezterm
export EDITOR="nvim"
export LANG="en_US.UTF-8"
export MANPAGER="nvim +Man!"
export XDG_SESSION_TYPE=wayland
export GDK_BACKEND=wayland
export QT_QPA_PLATFORM=wayland
export CLUTTER_BACKEND=wayland
export ELECTRON_OZONE_PLATFORM_HINT=wayland
export MOZ_ENABLE_WAYLAND=1

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# cargo
. "$HOME/.cargo/env"

